### PR TITLE
[FEAT] Support continue_blackout in timer payload

### PR DESCRIPTION
**Pull request by Shailesh351**
Part of https://github.com/WideChat/Rocket.Chat/issues/1002

i.e.
```
{
  "action": {
    "name": "df_set_timeout",
    "params": {
      "time": "7",
      "continue_blackout": true,
      "eventName": "payload2"
    }
  }
}
```

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 is this feature now ready to be tested?

**Comment by Shailesh351** [comment]
@ear-dev, Yes The basic glow for the timer payload which Meis have implemented works now. More complex flows i.e. reboot modem is pending. We planned to do it as separate story after it's done from fulfillment side

**Comment by ear-dev** [comment]
@Shailesh351 can you fix the merge conflict please?

**Comment by ear-dev** [comment]
@AlexanderKanakis can you review please?  thanks...

**Review by ear-dev — APPROVED** [review]
looks good..  thanks!

**Pull request merged**
