### PR TITLE
[NEW] DF setting to enable composer on trigger

### PR DESCRIPTION
**Pull request by bhardwajaditya**
https://github.com/WideChat/Rocket.Chat/issues/1030

Set it to true for ES agent and false for CX agent

image

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis please take note of this.  I can test it against the master branch, and maybe we will merge it there.....  but we have to add it to the json config once we are ready to merge the cx_reusable branch.  Is there much work involved in that?

**Comment by ear-dev** [comment]
@bhardwajaditya @AlexanderKanakis can we recreate this PR to be against alexanders assign_persistent_agent_configs_to_room branch instead of master?  At the moment we're in a bit of a bad state testing master against RC develop_pwa.  Also, this feature will only be used after we get the full cx_

**Comment by ear-dev** [comment]
@bhardwajaditya any chance you can move this PR to be against the assign_persistent_agent_configs_to_room branch please?  thanks.

**Comment by ear-dev** [comment]
@bhardwajaditya the cx_reusable branch is now completely up to date, and the only thing missing is this PR.  Can you please recreate this PR against that branch.  Then we will be feature complete for the moment, and ready to merge this into master. Thanks!

**Comment by bhardwajaditya** [comment]
@ear-dev I made the changes, but I am not able to see the json style config in Rocket.Chat App settings, is there anything else required for that? For that reason this is not tested from my end

**Comment by ear-dev** [comment]
@bhardwajaditya did you deploy the cx_reusable branch of Dialogflow to your server?  That should have the json config settings.

**Comment by bhardwajaditya** [comment]
@ear-dev yes I have deployed the correct branch along with the latest server version. It's a bit different for me.

image

**Comment by ear-dev** [comment]
@AlexanderKanakis what might Aditya be missing to get the proper configuration list view with individual json files per agent?

**Comment by AlexanderKanakis** [comment]
@bhardwajaditya Can you try uninstalling and re-installing the app? Are you running an instance of apps-engine that may override apps-engine in the server's modules?

**Comment by AlexanderKanakis** [comment]
@bhardwajaditya You can also try running `meteor npm install @rocket.chat/apps-engine` to make sure that you have the latest version of apps-engine in your modules.

**Comment by bhardwajaditya** [comment]
@AlexanderKanakis I tried doing that, so I observed there was a difference in server apps-engine version and DF app version. So I changed the version in the RC server to the following. Can you please confirm if it's same for you as well.

**git+https://github.com/WideChat/Rocket.Chat.Apps-engine.git#multicode_setting_type**

**Comment by AlexanderKanakis** [comment]
@bhardwajaditya Yes this is the correct branch. After changing it in the `package.json` and `package-lock.json` in the server and Apps.Dialogflwo, run `meteor npm install @rocket.chat/apps-engine` in both repos.

**Comment by bhardwajaditya** [comment]
@ear-dev this branch is fixed and tested on my end. The problem got fixed post updation of server.
@AlexanderKanakis thanks for the help

**Comment by bhardwajaditya** [comment]
@ear-dev I found an issue with cx_reusable branch, the end chat by visitor event was wrongly configured. It was resulting in error on chat close by visitor. It was just mapping error in migration. I have fixed it in this PR, it was a single line change.

https://github.com/WideChat/Apps.Dialogflow/pull/127/files#diff-d2118be21b218ce9410c5ee7cc95a856669b2f208b66f3a644a4d506d63ee466R162

**Comment by ear-dev** [comment]
Thanks Aditya........  @AlexanderKanakis can you review please....

**Review by AlexanderKanakis — APPROVED** [review]
Looks good. Thank you @bhardwajaditya for the close event fix!

**Pull request merged**
