### PR TITLE
[IMPROVEMENT] 1st Stage of whatsapp integration.

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
# Changes

### Image/PDF URL cards:

Custom payload in route fulfillment:
```
{
  "customFields": {
    "imageCardURL": [
      "http://www.africau.edu/images/default/sample.pdf"
    ]
  }
}
```
Result:
201251360_3819555124840666_1501453198199186802_n

### Link Cards

Plain text in Route Fulfillment:

> Your link is: https://www.twilio.com/docs/whatsapp

Result:
image

### Delayed Events

Custom payload in route fulfillment:
```
{
  "action": {
    "name": "df_set_timeout",
    "params": {
      "time": "7",
      "eventName": "Delay_Event"
    }
  }
}
```

| Parameter | Description                                 |
|-----------|---------------------------------------------|
| time      | Delay time in seconds                       |
| eventName | Name of Event to be activated after timeout |

### Changing Language (English, Portuguese)

Request by Guest:

> Portugues

or

> English 

### Guest WhatsApp number:

The guest's WhatsApp number is automatically stored in the Agent's session parameter **"username"** at the beginning of the session. Can be called using **"$session.params.username"**

### Session Timeout

It is determined by the **Customer Time-Out Time ** setting in the Apps.Dialogflow App settings. After timeout the session ends and all new conversations with the guest start in a new room from that start of the conversation flow.

### Close Chat

Custom payload in route fulfillment:
```
{
  "action": {
    "name": "df_close_chat"
  }
}
```

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you review please?  thanks!

**Comment by ear-dev** [comment]
@Shailesh351 is there any chance you can get to this review before Friday?  Also the accompanying PR on our RC repo please......  we'd like to have our full testbed setup before I go on vacation...  thanks!

**Comment by Shailesh351** [comment]
@ear-dev I thought the scheduler API changes for timeout are not ready as we discussed in the meeting yesterday. I will try to test it as soon as possible

**Comment by ear-dev** [comment]
@Shailesh351 @AlexanderKanakis Oh right....  does this PR also include the scheduler changes we wanted to back out and put in the SF app?

If so, @AlexanderKanakis can you clean up this PR so we can merge.....  maybe do that first before implementing the SF change?  Thanks.

**Comment by ear-dev** [comment]
In general......  maybe this is a case where there are too many unrelated functionalities in one PR.  We should avoid omnibus PRs and keep the PRs to single changes if possible moving forward.  Thanks.

**Comment by AlexanderKanakis** [comment]
@Shailesh351  @ear-dev Done!

**Comment by Shailesh351** [comment]
@AlexanderKanakis Getting this while deploying App

```
Shells-MacBook-Pro:Apps.Dialogflow shell$ rc-apps deploy --url http://localhost:3000 --username username --password password
   Starting App Deployment to Server

   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  There must be an exported class "DialogflowApp" or a default export in the main class file.
```

**Comment by AlexanderKanakis** [comment]
> @AlexanderKanakis Getting this while deploying App
> 
> ```
> Shells-MacBook-Pro:Apps.Dialogflow shell$ rc-apps deploy --url http://localhost:3000 --username username --password password
>    Starting App Deployment to Server
> 
>    Getting Server Info... ✓
>    Packaging the app... ✖
>  ›   Error:    ⟿  There must be an exported class "DialogflowApp" or a default export in the main class file.
> ```

Can you pull from the Branch again and re-deploy? thanks!

**Comment by Shailesh351** [comment]
@AlexanderKanakis Nice work! I was able to get pdf and images on WhatsApp.

I tried passing multiple URLs in `customFields.imageCardURL` Array and only the first one was appearing on whatsapp. 
Does it support only one file/attachment as of now?

Can you let me know the steps to test language steps? Also exported agent if possible.

Thanks!!

**Comment by Shailesh351** [comment]
@AlexanderKanakis @ear-dev The changes in this PR looks more like `Removing Timeout/Scheduler Stuff` So I think we are good to merge anyway

**Comment by AlexanderKanakis** [comment]
@Shailesh351 Unfortunately, Whatsapp supports only one media file per message. 

For the language changing functionality:
I created an entity with the name @custom_languageCode with the following setup:
image
Then I created a CX intent that extracts and sets the value of @custom_languageCode.
image

**Pull request merged**
