### PR TITLE
[FIX] App Persistence not Updating after Initial Creation of Data

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Potentially temporary fix, by deleting persistent data and re-creating it.

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you look at this when you get a chance please?  Alexander thinks this might be a 'temporary' fix? Do you think this is the best fix?

**Comment by Shailesh351** [comment]
@ear-dev Looking into it 👍

**Comment by Shailesh351** [comment]
@ear-dev Update: I just checked DB and the issue is because there are separate entries for persisting language and agentConfig. And when updating language it updates agentConfig data. So. we lose agentConfig and also language is not updated as well.

I'm working on the fix 👍 

Screenshot 2022-03-03 at 9 40 03 AM

**Comment by ear-dev** [comment]
good catch Shailesh!  thanks...

**Comment by Shailesh351** [comment]
Closing in favor of https://github.com/WideChat/Apps.Dialogflow/pull/144

**Pull request closed without merging**
