### PR TITLE
[FEAT] Wait for a response from the CX agent before sending any new messages from the visitor. Drop new visitor messages

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/1002

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 what happens in the case that we get no response at all from the dialogflow agent for some reason?  We likely do not want to be stuck forever....  :-)

**Comment by Shailesh351** [comment]
@ear-dev If we don't get any response from the Dialogflow, it will eventually timeout the request. And I'm clearing the processing state for any API errors. So I think we are good

**Comment by ear-dev** [comment]
@Shailesh351 one more question about this design please.......  In the case of a timer payload from the DF.agent, where the agent sends a payload to Rocketchat that says wait 5 seconds, and send me another timer_event (That's our timer loop)....

- In this case I imagine we reset our queue, because it's a response from CX, is that correct?
- And when our DF.app sends the next timer_event back to CX, the queue gets blocked again?  i.e. it does not have to be a message from the visitor to do the blocking....
- And, if the visitor were to sneak a message in during the 5 second wait time, that message would get through to CX?  And what would happen to the timer_event that our DF.app was waiting to send back?

Our desired behavior would be that if the visitor sneaks a message in while our DF.app were waiting (5 seconds) to send the next timer_event, we would like the visitor's message to get through, and have Df.app drop the upcoming timer_event it is waiting to send.  In this way, we would let the DF.agent handle the flow by sending a message back to the visitor saying something like "please wait while I process your previous request" and then allow it to start the timer loop again. 

What do you think will be the current behavior with this PR as is?  Thanks.

**Comment by Shailesh351** [comment]
@ear-dev We are only dropping messages sent by visitors. So all the other actions/scheduled tasks work as it is.

So if the visitor sneaks a message in while our DF.app has scheduled to send the next timer_event after 5 seconds, DF will still get that message and will revert back with the response. Scheduled timer_event will be triggered independently.

Can you please tell me what is the use case of timer_event? What are we trying to accomplish? Is this a special case with timer event that we want to handle specifically?

**Comment by ear-dev** [comment]
@Shailesh351 I have not been able to get this to work yet.  I am not seeing the log point, and I am seeing multiple responses instead of just the first one which I would have expected.

**Comment by ear-dev** [comment]
@chadgoss can you provide the name of the timer event?

New behavior: if the DF.app is waiting on a timer event, and the visitor sneaks a message in, let the message through, and drop the timer event.

**Comment by Shailesh351** [comment]
@ear-dev I tested it again and it's working for me. I confirmed that we only got two msgs in the Dialogflow console. 

One case I can think of is When DF calls fulfillment it takes some time for processing the request and after processing, it sends msg using the `/incoming` endpoint. We are currently not waiting for a response from fulfillment.  It accepts the next msg from the user as soon as DF App receives a response from DF agent.

Screenshot 2021-12-02 at 1 06 46 PM
Screenshot 2021-12-02 at 1 07 12 PM
Screenshot 2021-12-02 at 1 39 03 PM

**Comment by ear-dev** [comment]
@Shailesh351 after the latest catchup merges, will DF.app need the new apps engine update?  I see you have it here, but I don't want to be dependent on this PR to start testing the new RC builds.  Should we also make a separate PR against this repo, and maybe SF.app to use the new apps engine?

**Comment by Shailesh351** [comment]
@ear-dev Looking into it

**Comment by ear-dev** [comment]
@Shailesh351 this looks good.....  works for me.  @AlexanderKanakis can you review please and hit the approve button when you think it's ready.  Thanks!

**Review by AlexanderKanakis — APPROVED** [review]
Looks good and runs locally. Additional thank yous to @Shailesh351 for removing some unnecessary imports!

**Pull request merged**
