### PR TITLE
[EXTEND] Get App Settings from Multiple Agents

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Example:
Screenshot from 2021-11-18 16-34-36

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis this looks like a single json and not one per agent?  Also, can you have the json template example show up formated.pretty()?  Thanks.......

image

**Comment by AlexanderKanakis** [comment]
> @AlexanderKanakis this looks like a single json and not one per agent? Also, can you have the json template example show up formated.pretty()? Thanks.......
> 
> image

A new setting type can only be created in RC, please make you you also use this RC PR: https://github.com/WideChat/Rocket.Chat/pull/981

I would also recommend you delete the app from your DB and reinstall

**Comment by ear-dev** [comment]
@AlexanderKanakis I am now testing with both your server PR and this DF PR........  but now I cannot reach the DF admin UI.  It just shows a blank screen and I can see these errors in the console using devtools.......  any ideas?  thanks.

```
modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:42728 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `APIsDisplay`. See https://reactjs.org/link/warning-keys for more information.
    at APIsDisplay (/client/views/admin/apps/APIsDisplay.tsx:51:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at div
    at div
    at Scrollbars (/node_modules/rc-scrollbars/lib/Scrollbars/index.js:78:28)
    at WrappedComponent (/client/components/ScrollableContentWrapper.tsx:70:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at PageScrollableContent (/client/components/Page/PageScrollableContent.tsx:53:5)
    at PageScrollableContentWithShadow (/client/components/Page/PageScrollableContentWithShadow.tsx:63:5)
    at section
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at Page (/client/components/Page/Page.tsx:44:31)
    at AppDetailsPage (/client/views/admin/apps/AppDetailsPage.js:136:5)
    at AppsProvider (/client/views/admin/apps/AppsProvider.tsx:85:5)
    at AppsRoute (/client/views/admin/apps/AppsRoute.js:111:35)
    at Suspense
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at AdministrationLayout (/client/views/admin/AdministrationLayout.tsx:30:5)
    at AdministrationRouter (/client/views/admin/AdministrationRouter.js:59:5)
    at Suspense
    at WrappedComponent (https://dev.livechat.acc.viasat.io/app/app.js?hash=edb14d4db99f9dda40b2c9f2beb3dbcbbeec8feb:73543:31)
    at AppLayout (/client/views/root/AppLayout.tsx:65:22)
    at AttachmentProvider (/client/components/Message/Attachments/providers/AttachmentProvider.tsx:58:5)
    at ModalProvider (/client/providers/ModalProvider.tsx:66:5)
    at OmnichannelProvider (/client/providers/OmnichannelProvider.tsx:118:5)
    at AuthorizationProvider (/client/providers/AuthorizationProvider.tsx:92:5)
    at UserProvider (/client/providers/UserProvider.tsx:105:5)
    at CustomSoundProvider (/client/providers/CustomSoundProvider.tsx:33:5)
    at AvatarUrlProvider (/client/providers/AvatarUrlProvider.tsx:68:5)
    at LayoutProvider (/client/providers/LayoutProvider.tsx:67:5)
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at ToastMessagesProvider (/client/providers/ToastMessagesProvider.tsx:64:5)
    at SidebarProvider (/client/providers/SidebarProvider.tsx:50:5)
    at SessionProvider (/client/providers/SessionProvider.tsx:46:5)
    at TranslationProvider (/client/providers/TranslationProvider.js:130:5)
    at RouterProvider (/client/providers/RouterProvider.tsx:96:5)
    at ServerProvider (/client/providers/ServerProvider.tsx:110:5)
    at ConnectionStatusProvider (/client/providers/ConnectionStatusProvider.tsx:52:5)
    at MeteorProvider (/client/providers/MeteorProvider.tsx:131:5)
    at Suspense
    at AppRoot
printWarning @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:42728
error @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:42704
validateExplicitKey @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:44560
validateChildKeys @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:44586
createElementWithValidation @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:44741
eval @ APIsDisplay.tsx:40
eval @ APIsDisplay.tsx:36
APIsDisplay @ APIsDisplay.tsx:31
renderWithHooks @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339
mountIndeterminateComponent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165
beginWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403
beginWork$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69294
performUnitOfWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133
workLoopSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061
renderRootSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68024
performSyncWorkOnRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67647
(anonymous) @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56681
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushSyncCallbackQueueImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56676
flushSyncCallbackQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56663
scheduleUpdateOnFiber @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67247
dispatchAction @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:61493
fetchAppInfo @ useAppInfo.ts:85
await in fetchAppInfo (async)
eval @ useAppInfo.ts:88
invokePassiveEffectCreate @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68841
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
flushPassiveEffectsImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68928
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushPassiveEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68801
flushDiscreteUpdates @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67710
flushDiscreteUpdatesIfNeeded @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49122
dispatchDiscreteEvent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:51240
CodeSettingInput.js:173 Uncaught TypeError: agentList.map is not a function
    at MultiCodeSettingInput (CodeSettingInput.js:173)
    at renderWithHooks (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339)
    at mountIndeterminateComponent (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165)
    at beginWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403)
    at HTMLUnknownElement.callCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299)
    at Object.invokeGuardedCallbackDev (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348)
    at invokeGuardedCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410)
    at beginWork$1 (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318)
    at performUnitOfWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133)
    at workLoopSync (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061)
MultiCodeSettingInput @ CodeSettingInput.js:173
renderWithHooks @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339
mountIndeterminateComponent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165
beginWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
beginWork$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318
performUnitOfWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133
workLoopSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061
renderRootSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68024
performSyncWorkOnRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67647
(anonymous) @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56681
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushSyncCallbackQueueImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56676
flushSyncCallbackQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56663
scheduleUpdateOnFiber @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67247
dispatchAction @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:61493
fetchAppInfo @ useAppInfo.ts:85
await in fetchAppInfo (async)
eval @ useAppInfo.ts:88
invokePassiveEffectCreate @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68841
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
flushPassiveEffectsImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68928
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushPassiveEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68801
flushDiscreteUpdates @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67710
flushDiscreteUpdatesIfNeeded @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49122
dispatchDiscreteEvent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:51240
modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:65439 The above error occurred in the <MultiCodeSettingInput> component:

    at MultiCodeSettingInput (/client/views/admin/settings/inputs/CodeSettingInput.js:120:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at Field
    at MemoizedSetting (/client/views/admin/settings/MemoizedSetting.js:167:5)
    at AppSetting (/client/views/admin/apps/AppSetting.js:97:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at AppSettingsAssembler (/client/views/admin/apps/AppSettingsAssembler.js:40:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at SettingsDisplay (/client/views/admin/apps/SettingsDisplay.tsx:67:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at div
    at div
    at Scrollbars (/node_modules/rc-scrollbars/lib/Scrollbars/index.js:78:28)
    at WrappedComponent (/client/components/ScrollableContentWrapper.tsx:70:5)
    at div
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at PageScrollableContent (/client/components/Page/PageScrollableContent.tsx:53:5)
    at PageScrollableContentWithShadow (/client/components/Page/PageScrollableContentWithShadow.tsx:63:5)
    at section
    at Box (https://dev.livechat.acc.viasat.io/packages/modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:16871:24)
    at Page (/client/components/Page/Page.tsx:44:31)
    at AppDetailsPage (/client/views/admin/apps/AppDetailsPage.js:136:5)
    at AppsProvider (/client/views/admin/apps/AppsProvider.tsx:85:5)
    at AppsRoute (/client/views/admin/apps/AppsRoute.js:111:35)
    at Suspense
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at AdministrationLayout (/client/views/admin/AdministrationLayout.tsx:30:5)
    at AdministrationRouter (/client/views/admin/AdministrationRouter.js:59:5)
    at Suspense
    at WrappedComponent (https://dev.livechat.acc.viasat.io/app/app.js?hash=edb14d4db99f9dda40b2c9f2beb3dbcbbeec8feb:73543:31)
    at AppLayout (/client/views/root/AppLayout.tsx:65:22)
    at AttachmentProvider (/client/components/Message/Attachments/providers/AttachmentProvider.tsx:58:5)
    at ModalProvider (/client/providers/ModalProvider.tsx:66:5)
    at OmnichannelProvider (/client/providers/OmnichannelProvider.tsx:118:5)
    at AuthorizationProvider (/client/providers/AuthorizationProvider.tsx:92:5)
    at UserProvider (/client/providers/UserProvider.tsx:105:5)
    at CustomSoundProvider (/client/providers/CustomSoundProvider.tsx:33:5)
    at AvatarUrlProvider (/client/providers/AvatarUrlProvider.tsx:68:5)
    at LayoutProvider (/client/providers/LayoutProvider.tsx:67:5)
    at SettingsProvider (/client/providers/SettingsProvider.tsx:92:5)
    at ToastMessagesProvider (/client/providers/ToastMessagesProvider.tsx:64:5)
    at SidebarProvider (/client/providers/SidebarProvider.tsx:50:5)
    at SessionProvider (/client/providers/SessionProvider.tsx:46:5)
    at TranslationProvider (/client/providers/TranslationProvider.js:130:5)
    at RouterProvider (/client/providers/RouterProvider.tsx:96:5)
    at ServerProvider (/client/providers/ServerProvider.tsx:110:5)
    at ConnectionStatusProvider (/client/providers/ConnectionStatusProvider.tsx:52:5)
    at MeteorProvider (/client/providers/MeteorProvider.tsx:131:5)
    at Suspense
    at AppRoot

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:65439
update.callback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:65472
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:57672
commitUpdateQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:57693
commitLifeCycles @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:66090
commitLayoutEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68780
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
commitRootImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68505
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
commitRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68344
performSyncWorkOnRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67683
(anonymous) @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56681
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushSyncCallbackQueueImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56676
flushSyncCallbackQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56663
scheduleUpdateOnFiber @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67247
dispatchAction @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:61493
fetchAppInfo @ useAppInfo.ts:85
await in fetchAppInfo (async)
eval @ useAppInfo.ts:88
invokePassiveEffectCreate @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68841
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
flushPassiveEffectsImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68928
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushPassiveEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68801
flushDiscreteUpdates @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67710
flushDiscreteUpdatesIfNeeded @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49122
dispatchDiscreteEvent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:51240
useAppInfo.ts:86 Uncaught (in promise) TypeError: agentList.map is not a function
    at MultiCodeSettingInput (CodeSettingInput.js:173)
    at renderWithHooks (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339)
    at mountIndeterminateComponent (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165)
    at beginWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403)
    at HTMLUnknownElement.callCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299)
    at Object.invokeGuardedCallbackDev (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348)
    at invokeGuardedCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410)
    at beginWork$1 (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318)
    at performUnitOfWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133)
    at workLoopSync (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061)
MultiCodeSettingInput @ CodeSettingInput.js:173
renderWithHooks @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339
mountIndeterminateComponent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165
beginWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
beginWork$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318
performUnitOfWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133
workLoopSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061
renderRootSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68024
performSyncWorkOnRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67647
(anonymous) @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56681
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushSyncCallbackQueueImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56676
flushSyncCallbackQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56663
scheduleUpdateOnFiber @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67247
dispatchAction @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:61493
fetchAppInfo @ useAppInfo.ts:85
await in fetchAppInfo (async)
eval @ useAppInfo.ts:88
invokePassiveEffectCreate @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68841
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
flushPassiveEffectsImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68928
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushPassiveEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68801
flushDiscreteUpdates @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67710
flushDiscreteUpdatesIfNeeded @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49122
dispatchDiscreteEvent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:51240
```

**Comment by AlexanderKanakis** [comment]
@ear-dev If you get a blank screen that is indeed an issue with the client. Do you get anything else besides the warning?

**Comment by ear-dev** [comment]
@AlexanderKanakis I also get this error:

```
useAppInfo.ts:86 Uncaught (in promise) TypeError: agentList.map is not a function
    at MultiCodeSettingInput (CodeSettingInput.js:173)
    at renderWithHooks (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339)
    at mountIndeterminateComponent (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165)
    at beginWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403)
    at HTMLUnknownElement.callCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299)
    at Object.invokeGuardedCallbackDev (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348)
    at invokeGuardedCallback (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410)
    at beginWork$1 (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318)
    at performUnitOfWork (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133)
    at workLoopSync (modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061)
MultiCodeSettingInput @ CodeSettingInput.js:173
renderWithHooks @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:60339
mountIndeterminateComponent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:63165
beginWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:64403
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
beginWork$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:69318
performUnitOfWork @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68133
workLoopSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68061
renderRootSync @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68024
performSyncWorkOnRoot @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67647
(anonymous) @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56681
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushSyncCallbackQueueImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56676
flushSyncCallbackQueue @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56663
scheduleUpdateOnFiber @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67247
dispatchAction @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:61493
fetchAppInfo @ useAppInfo.ts:85
await in fetchAppInfo (async)
eval @ useAppInfo.ts:88
invokePassiveEffectCreate @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68841
callCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49299
invokeGuardedCallbackDev @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49348
invokeGuardedCallback @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49410
flushPassiveEffectsImpl @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68928
unstable_runWithPriority @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:72158
runWithPriority$1 @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:56630
flushPassiveEffects @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:68801
flushDiscreteUpdates @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:67710
flushDiscreteUpdatesIfNeeded @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:49122
dispatchDiscreteEvent @ modules.js?hash=3611583cfffa9af360ae41f6051e4b6fa0c2c8e9:51240
```

**Comment by AlexanderKanakis** [comment]
@ear-dev Yup, that's the issue. I'm looking into it

**Comment by AlexanderKanakis** [comment]
@ear-dev The issue was with the default value RC got from the app settings. If there were no entries in the database RC would parse the default value as an object and not a mappable array.

Make sure to:

1. Pull from `get_app_settings_from_json`.
2. Delete all records of Apps.Dialogflow from your local server.
3. Restart the server.
4. Deploy the app.

**Comment by ear-dev** [comment]
@AlexanderKanakis does uninstalling the current DF.app accomplish the same thing?  Or do we actually need to go into the database and do some surgery to remove entries?  If it is the later, can you please provide information on exactly the tables and rows that will need to be removed?  Thanks...

**Comment by AlexanderKanakis** [comment]
@ear-dev Uninstalling the app should work fine.

**Pull request merged**
