### PR TITLE
[EXTEND] Multiple Agents Config Setting || Connection Draining Fix with Persistent Endpoints

### PR DESCRIPTION
**Pull request by AlexanderKanakis**

### CODE REVIEW

**Comment by ear-dev** [comment]
@AlexanderKanakis this is working great in conjunction with the RC PR.....  nice job!  @Shailesh351 can you review please?  thanks...

**Review by Shailesh351 — COMMENTED** [review]
@ear-dev @AlexanderKanakis I understand that we are moving to JSON config-based UI for automating through CICD and supporting multiple agents. 

But when I was testing it was difficult to modify any setting as there is no label/description. Maybe we should have some documentation on the App Settings page?

It also becomes more error-prone as we are moving away from RC's Typed Settings Structure to just JSON.

**Comment by ear-dev** [comment]
> But when I was testing it was difficult to modify any setting as there is no label/description. Maybe we should have some documentation on the App Settings page?

@Shailesh351 We do have a default agent that displays a default config.json file.  It should have all the options in it.  But perhaps you are asking about some description of each value.  Do you guys think a full description of each value would be too cluttered for the app settings page, or should we just make a wiki?

**Review by Shailesh351 — APPROVED** [review]
Tested and verified. Looks good to me. Thanks @AlexanderKanakis!!

**Comment by ear-dev** [comment]
Thanks guys!

**Pull request merged**
