### PR TITLE
[REFACTOR] Scheduler API  Code

### PR DESCRIPTION
**Pull request by Shailesh351**
Part of https://github.com/WideChat/Rocket.Chat/issues/887

### CODE REVIEW

**Comment by chadgoss** [comment]
@Shailesh351 can you please update (if necessary) following your 3.17.1 merge? thanks!

**Comment by chadgoss** [comment]
@AlexanderKanakis can you please review? thanks!

**Comment by Shailesh351** [comment]
@chadgoss I have reverted canceling job changes. So this PR is now only for refactoring code

**Comment by chadgoss** [comment]
@Shailesh351 I pulled this and tested, I'm seeing that disable input payloads are not getting enforced

[08/19/2021 01:59:42 PM] [PAYLOAD] in views.webhook: [Session_ID: xbJeNjz99cbyRYcTk] Webhook Response: ({'outputContexts': [], 'fulfillment_messages': [{'text': {'text': ['We have several options for changing to a Vacation Plan.']}}, {'text': {'text': ['Vacation Plans start at $9.99 a month. Other fees may also apply.  <a href="https://help.viasat.com/s/article/Temporarily-suspending-your-Viasat-service" target="_blank" ping="http://forward.dev.acc.viasat.io:8001/api/v1/ping/link_slug__hibernation_plan/eizcqfcu">Additional information on Hibernation and Vacation Plans</a>']}}, {'payload': {'quick_replies': [{'content_type': 'text', 'title': 'Continue', 'payload': 'Continue'}]}}, {'payload': {'quickReplies': {'options': [{'text': 'Continue', 'buttonStyle': 'primary'}]}}}, {'payload': {'disableInput': True, 'disableInputMessage': 'Please select from the provided options'}}, {'payload': {'customFields': {'disableInput': True, 'disableInputMessage': 'Please select from the provided options', 'displayTyping': False}}}], 'followupEventInput': {}}, 200)

**Comment by chadgoss** [comment]
Screen Shot 2021-08-19 at 2 02 44 PM

**Comment by Shailesh351** [comment]
This PR does not have any change related to disableInput. Can you test by switching back to cx_development? If you still see the same, the issue is different. Maybe in Livechat Repo.

**Pull request merged**
