### PR TITLE
Fix Typing Indicator

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/689

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 I'm still seeing the same issue.  It's kind of flaky, but it does happen a lot of the time.  Thoughts?

**Comment by Shailesh351** [comment]
Man, this one is a persistent one!!. Actually, I'm not able to test it completely as I don't have fulfillment running to debug in depth.
I will check @ear-dev.

**Comment by Shailesh351** [comment]
@ear-dev This PR now finally fixes typing indicator. I have tested by mocking fulfilment behaviour using postman by calling apps fulfilment endpoint.

**Comment by chadgoss** [comment]
tested and verified

**Pull request merged**
