### PR TITLE
[IMPROVEMENT] Response message read order handling

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Ensures that all text messages are read and sent to client before custom payloads and other fulfillment dialog options.

### CODE REVIEW

**Comment by stetak** [comment]
I still messages being dropped. Room id g6WigbXuKA3PkkgBN on https://ba.messaging.vega-preprod.viasat.io/omnichannel/current - The message dropped before the boleto link was : "You can download your boleto below."

@AlexanderKanakis @ear-dev

**Comment by ear-dev** [comment]
@AlexanderKanakis do you think you can repro the issue that @stetak is seeing?

**Comment by AlexanderKanakis** [comment]
@stetak @AlexanderKanakis  Dialogflow merged the all custom payloads with the last text message of the response. It worked in the context of the previous custom payloads (customFields), but the mediaCard needed to be separated. It should be fixed now

**Comment by ear-dev** [comment]
Thanks @AlexanderKanakis I'll deploy and test this tomorrow

**Comment by ear-dev** [comment]
@AlexanderKanakis We tested this and it's fixed!  Awesome, thanks......  

@bhardwajaditya can you review this one please?  Just take a quick look and if it looks good I'll merge...  thanks!

**Review by bhardwajaditya — APPROVED** [review]

**Pull request merged**
